### ISSUE TITLE
KiCost no longer works with StickIt-Hat.xml test file

### ISSUE THREAD

**Issue by xesscorp** [hildogjr/KiCost#246]
When I issue the command:

```terminal
kicost -i StickIt-Hat.xml -wqs
```
I get an exception:

```
Progress:   0%|                                                                       | 0/16 [00:00<?, ?part/s]
Traceback (most recent call last):
  File "C:\Python36-32\Scripts\kicost-script.py", line 11, in <module>
    load_entry_point('kicost', 'console_scripts', 'kicost')()
  File "c:\xesscorp\kicad\tools\kicost\kicost\__main__.py", line 275, in main
    local_currency=args.currency)
  File "c:\xesscorp\kicad\tools\kicost\kicost\kicost.py", line 261, in kicost
    id, url, part_num, price_tiers, qty_avail, info_dist = scrape_part(args)
  File "c:\xesscorp\kicad\tools\kicost\kicost\distributors\web_routines.py", line 204, in scrape_part
    price_tiers[d] = dist_module.get_price_tiers(html_tree)
  File "c:\xesscorp\kicad\tools\kicost\kicost\distributors\local\local.py", line 130, in get_price_tiers
    qty, price = qty_price.split(SEPRTR)
ValueError: too many values to unpack (expected 2)
```
This is caused by the pricing data entered in the XML file for parts PM1, JP1, and JP8. When these parts are removed, the file is processed without errors.

I traced the cause of this error to the changes made in commit c325f01ab778771af998a6c98a21993b06edc4a0 .

**Comment by hildogjr** [comment]
Just need to be checked with the price is correctly propagated for designators that used the local distributor template.
