### ISSUE TITLE
Keeps failing with: NameError: global name 'pn' is not defined

### ISSUE THREAD

**Issue by MrSurly** [hildogjr/KiCost#302]
#### Issue / Problem report

Pulled the repo today (6c3d17b5321f99ae1274e1b6eab0a0a1bcb30453)

```
$ kicost -i main.xml --include digikey  --variant bat_pwr --overwrite --debug
Received 403, scraper possibly detected: Starting new session for https://www.digikey.com                                                   
Received 403, scraper possibly detected: Starting new session for https://www.digikey.com                                                   
Received 403, scraper possibly detected: Starting new session for https://www.digikey.com                                                   
Received 403, scraper possibly detected: Starting new session for https://www.digikey.com                                                   
No 'digikey#' or 'manf#' field: cannot lookup part [] at digikey.                                                                           
No 'digikey#' or 'manf#' field: cannot lookup part [] at digikey.                                                                           
Received 403, scraper possibly detected: Starting new session for https://www.digikey.com                                                   
Progress:  30%|███████████████████████████                                                                | 11/37 [03:50<08:34, 19.79s/part]Traceback (most recent call last):
  File "/home/epoulsen/.local/bin/kicost", line 11, in <module>
    load_entry_point('kicost==0.1.47', 'console_scripts', 'kicost')()
  File "/home/epoulsen/.local/lib/python2.7/site-packages/kicost-0.1.47-py2.7.egg/kicost/__main__.py", line 286, in main
    local_currency=args.currency)
  File "/home/epoulsen/.local/lib/python2.7/site-packages/kicost-0.1.47-py2.7.egg/kicost/kicost.py", line 289, in kicost
    scrape_result = distributor_dict[d]['instance'].scrape_part(i, parts[i])
  File "/home/epoulsen/.local/lib/python2.7/site-packages/kicost-0.1.47-py2.7.egg/kicost/distributors/distributor.py", line 128, in scrape_part
    html_tree, url = self.get_part_html_tree(part)
  File "/home/epoulsen/.local/lib/python2.7/site-packages/kicost-0.1.47-py2.7.egg/kicost/distributors/distributor.py", line 166, in get_part_html_tree
    return self.dist_get_part_html_tree(part.fields[key], extra_search_terms)
  File "/home/epoulsen/.local/lib/python2.7/site-packages/kicost-0.1.47-py2.7.egg/kicost/distributors/digikey/digikey.py", line 353, in dist_get_part_html_tree
    descend=descend - 1)
  File "/home/epoulsen/.local/lib/python2.7/site-packages/kicost-0.1.47-py2.7.egg/kicost/distributors/digikey/digikey.py", line 308, in dist_get_part_html_tree
    self.merge_price_tiers(tree, ap_tree)
  File "/home/epoulsen/.local/lib/python2.7/site-packages/kicost-0.1.47-py2.7.egg/kicost/distributors/digikey/digikey.py", line 385, in merge_price_tiers
    self.logger.log(DEBUG_OBSESSIVE, 'Problem merging price tiers for Digikey part {} with alternate packaging!'.format(pn))
NameError: global name 'pn' is not defined
```

[main.zip](https://github.com/xesscorp/KiCost/files/2255034/main.zip)

**Comment by MrSurly** [comment]
:+1:
