### ISSUE TITLE
Kicost Gui on windows

### ISSUE THREAD

**Issue by AlkalineZN** [hildogjr/KiCost#420]
#### Issue / Problem report

Hello
I can no longer use kicost after a fresh installation.
I followed the step by step guide but continue to bring me this text:

(base) PS C:\WINDOWS\system32> kicost
Traceback (most recent call last):
  File "C:\Users\Oscar\anaconda3\Scripts\kicost-script.py", line 33, in <module>
    sys.exit(load_entry_point('kicost==1.1.4', 'console_scripts', 'kicost')())
  File "C:\Users\Oscar\anaconda3\lib\site-packages\kicost-1.1.4-py3.8.egg\kicost\__main__.py", line 253, in main
    kicost_gui() # Use the user gui if no input is given.
  File "C:\Users\Oscar\anaconda3\lib\site-packages\kicost-1.1.4-py3.8.egg\kicost\kicost_gui.py", line 1065, in kicost_gui
    frame = formKiCost(None)
  File "C:\Users\Oscar\anaconda3\lib\site-packages\kicost-1.1.4-py3.8.egg\kicost\kicost_gui.py", line 367, in __init__
    fgSizer1.Add(self.m_gauge_process, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)) || !(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at ..\..\src\common\sizer.cpp(1453) in wxGridSizer::DoInsert(): wxEXPAND flag will be overridden by alignment flags

The commands I used for the installation are as follows

easy_install Kicost

easy_install wxpython

kicost --setup

kicost

I am using anaconda

KiCost v.1.1.4.at Python 3.8.3.on Windows-10-10.0.19041-SP0(64bit).Graphical library: 4.1.0 msw (phoenix) wxWidgets 3.1.4.
Thanks for your help!

**Comment by hildogjr** [comment]
Duplicated of #412
