### ISSUE TITLE
Kicost GUI, unable to open in windows 10

### ISSUE THREAD

**Issue by gontiavasu** [hildogjr/KiCost#422]
I am unable to open the KiCost GUI in windows 10. I installed it first time. Any help will be appreciated.
I got the following error:
thank you!!

C:\Windows\system32>C:\Python37\Scripts\kicost
Traceback (most recent call last):
  File "C:\Python37\Scripts\kicost-script.py", line 11, in <module>
    load_entry_point('kicost==1.1.4', 'console_scripts', 'kicost')()
  File "C:\Python37\lib\site-packages\kicost-1.1.4-py3.7.egg\kicost\__main__.py", line 253, in main
    kicost_gui() # Use the user gui if no input is given.
  File "C:\Python37\lib\site-packages\kicost-1.1.4-py3.7.egg\kicost\kicost_gui.py", line 1065, in kicost_gui
    frame = formKiCost(None)
  File "C:\Python37\lib\site-packages\kicost-1.1.4-py3.7.egg\kicost\kicost_gui.py", line 367, in __init__
    fgSizer1.Add(self.m_gauge_process, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)) || !(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at ..\..\src\common\sizer.cpp(1453) in wxGridSizer::DoInsert(): wxEXPAND flag will be overridden by alignment flags

C:\Windows\system32>"C:\Python37\Scripts\kicost"
Traceback (most recent call last):
  File "C:\Python37\Scripts\kicost-script.py", line 11, in <module>
    load_entry_point('kicost==1.1.4', 'console_scripts', 'kicost')()
  File "C:\Python37\lib\site-packages\kicost-1.1.4-py3.7.egg\kicost\__main__.py", line 253, in main
    kicost_gui() # Use the user gui if no input is given.
  File "C:\Python37\lib\site-packages\kicost-1.1.4-py3.7.egg\kicost\kicost_gui.py", line 1065, in kicost_gui
    frame = formKiCost(None)
  File "C:\Python37\lib\site-packages\kicost-1.1.4-py3.7.egg\kicost\kicost_gui.py", line 367, in __init__
    fgSizer1.Add(self.m_gauge_process, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)) || !(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at ..\..\src\common\sizer.cpp(1453) in wxGridSizer::DoInsert(): wxEXPAND flag will be overridden by alignment flags

**Comment by hildogjr** [comment]
Duplicated from #412
Closing it to keep the ISSUEs list organized.
