### ISSUE TITLE
Fails to Start on Windows

### ISSUE THREAD

**Issue by ajayre** [hildogjr/KiCost#435]
Installed ActiveState python 3.8
easy_install kicost 1.1.4
pip install -U wxPython 4.1.1-cp38

running kicost I get:

`Traceback (most recent call last):
  File "C:\Python3\Scripts\kicost-script.py", line 33, in <module>
    sys.exit(load_entry_point('kicost==1.1.4', 'console_scripts', 'kicost')())
  File "C:\Python3\lib\site-packages\kicost-1.1.4-py3.8.egg\kicost\__main__.py", line 253, in main
    kicost_gui() # Use the user gui if no input is given.
  File "C:\Python3\lib\site-packages\kicost-1.1.4-py3.8.egg\kicost\kicost_gui.py", line 1065, in kicost_gui
    frame = formKiCost(None)
  File "C:\Python3\lib\site-packages\kicost-1.1.4-py3.8.egg\kicost\kicost_gui.py", line 367, in __init__
    fgSizer1.Add(self.m_gauge_process, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)) || !(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at ..\..\src\common\sizer.cpp(1523) in wxGridSizer::DoInsert(): wxEXPAND flag will be overridden by alignment flags
`

**Comment by hildogjr** [comment]
Duplicated of #428 and #412, please use the CLI (command line) interface while the fix is not provide.
