### ISSUE TITLE
Digikey API: pyopenssl 24.1.0 breaking change

### ISSUE THREAD

**Issue by Andrew-Collins** [hildogjr/KiCost#562]
Hi @set-soft,

When installing from source (or from the aur package):
```
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 7, in <module>
  File "/tmp/makepkg/kicost/src/KiCost-1.1.18/kicost/__init__.py", line 17, in <module>
    from .kicost import query_part_info, solve_parts_qtys  # noqa F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/makepkg/kicost/src/KiCost-1.1.18/kicost/kicost.py", line 61, in <module>
    from .edas.tools import field_name_translations, subpartqty_split, group_parts, PRJ_STR_DECLARE, PRJPART_SPRTR, partgroup_qty
  File "/tmp/makepkg/kicost/src/KiCost-1.1.18/kicost/edas/__init__.py", line 25, in <module>
    from .eda import eda_class
  File "/tmp/makepkg/kicost/src/KiCost-1.1.18/kicost/edas/eda.py", line 28, in <module>
    from ..distributors import get_distributors_iter
  File "/tmp/makepkg/kicost/src/KiCost-1.1.18/kicost/distributors/__init__.py", line 35, in <module>
    from .api_digikey import api_digikey  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/makepkg/kicost/src/KiCost-1.1.18/kicost/distributors/api_digikey.py", line 40, in <module>
    from kicost_digikey_api_v3 import by_digikey_pn, by_manf_pn, by_keyword, DigikeyError, DK_API
  File "/home/ac/.local/lib/python3.11/site-packages/kicost_digikey_api_v3/__init__.py", line 2, in <module>
    from kicost_digikey_api_v3.v3.api import (keyword_search, product_details, digi_reel_pricing, suggested_parts,
  File "/home/ac/.local/lib/python3.11/site-packages/kicost_digikey_api_v3/v3/api.py", line 4, in <module>
    import kicost_digikey_api_v3.oauth.oauth2
  File "/home/ac/.local/lib/python3.11/site-packages/kicost_digikey_api_v3/oauth/oauth2.py", line 23, in <module>
    from kicost_digikey_api_v3.certauth.certauth import CertificateAuthority
  File "/home/ac/.local/lib/python3.11/site-packages/kicost_digikey_api_v3/certauth/certauth.py", line 6, in <module>
    from OpenSSL import crypto
  File "/home/ac/.local/lib/python3.11/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/home/ac/.local/lib/python3.11/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/home/ac/.local/lib/python3.11/site-packages/OpenSSL/crypto.py", line 1623, in <module>
    class X509StoreFlags:
  File "/home/ac/.local/lib/python3.11/site-packages/OpenSSL/crypto.py", line 1642, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?
```

pyopenssl 24.1.0 seems to have introduced breaking changes, as pinning to 24.0.0 worked as described here:
https://github.com/conda/conda/issues/13619

**Comment by Andrew-Collins** [comment]
Thanks again for your work on these tools, if you would like I should have some time on Friday have crack at fixing this.

**Comment by set-soft** [comment]
Hi @Andrew-Collins !
The newest I have in my docker images is 24.0.0.
Note that the traceback says the problem is just doing: `from OpenSSL import crypto`, so it might be just some library version mismatch.

**Comment by Andrew-Collins** [comment]
Hi @set-soft,

This error will only occur on 'fresh' installs as the `kicost-digikey-api-v3` package does not restrict the version of `pyopenssl` it requires; so if `pyopenssl` is already installed then the build will use it as is, instead of pulling the latest from `pypi`.

If you build in a fresh venv, uninstall `pyopenssl`, or possibly rebuild your docker image it should start using the lastest `pyopenssl` version.

**Comment by Andrew-Collins** [comment]
This brings up the point that if we elect to make changes, that the `kicost-digikey-api-v3` package will need to specify `pyopenssl >= 24.1.0`...

**Comment by set-soft** [comment]
Hi @Andrew-Collins !

I run my "experimental" docker images (used for KiCad 8), and upgraded the package to 24.1.0, I then reinstalled the digikey API package. It installs and works.

So again: take a look at the traceback, the crash is inside the *pyopenssl* code and triggered by just requesting the crypto functionality (`from OpenSSL import crypto`). IMHO this is a package error. The libcrypto is most probably missing the *X509_V_FLAG_NOTIFY_POLICY* symbol. I don't know if your package is using a system level libcrypto, or one shipped with the python code (something regrettable, but very Pythonic), in any case I bet the version of libcrypto isn't the correct one.

If you find a problem in the code please open a new issue. Here I don't see anything we can do from the digikey API side.

**Comment by Andrew-Collins** [comment]
Hi @set-soft,

I'm very sorry, I misread and thought you were talking about the `pyopenssl` version mismatch :facepalm:

I was originally having this problem while building in a fresh venv, but I just tried again and was unable to replicate this error. Unsure what changed :upside_down_face:  

And for anyone else who may find this, my system level install was failing due to old versions of `pyopenssl` and `cryptography` that were installed at the system level.
